// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CardController from "./card_controller"
application.register("card", CardController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)


import MenuController from "./menu_controller"
application.register("menu", MenuController)

import ChatbotController from "./chatbot_controller"
application.register("chatbot", ChatbotController)
